name: marp-to-pages
concurrency: marp-to-pages
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy images
        run: mkdir build && cp -R img build/img

      - name: Build HTML from marp_slides.md
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: marp_slides.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Build PDF from marp_slides.md
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: marp_slides.md -o build/barschweg_expose.pdf
        env:
          MARP_USER: root:root

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: ./build/
